[2024-04-25T14:28:37.230+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Flow.create_tables scheduled__2024-04-11T21:11:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
