[2024-03-21T19:08:35.345+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Flow.create_tables manual__2024-03-20T16:26:04.128092+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
