[2024-03-14T19:06:49.648+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Flow.insert_data_from_files manual__2024-03-14T18:46:29.121714+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
