[2024-03-09T12:22:59.256+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Sales_ETL.snapshot manual__2024-03-09T11:56:38.365006+00:00 [queued]>
[2024-03-09T12:22:59.267+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Sales_ETL.snapshot manual__2024-03-09T11:56:38.365006+00:00 [queued]>
[2024-03-09T12:22:59.268+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-03-09T12:22:59.284+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): snapshot> on 2024-03-09 11:56:38.365006+00:00
[2024-03-09T12:22:59.290+0000] {standard_task_runner.py:60} INFO - Started process 1173 to run task
[2024-03-09T12:22:59.294+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Sales_ETL', 'snapshot', 'manual__2024-03-09T11:56:38.365006+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpillhf9pp']
[2024-03-09T12:22:59.295+0000] {standard_task_runner.py:88} INFO - Job 159: Subtask snapshot
[2024-03-09T12:22:59.352+0000] {task_command.py:423} INFO - Running <TaskInstance: Sales_ETL.snapshot manual__2024-03-09T11:56:38.365006+00:00 [running]> on host 3b9d9f11e4f2
[2024-03-09T12:22:59.400+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'snapshot', field 'sql'. Template: 'snapshot.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: snapshot.sql
[2024-03-09T12:22:59.402+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: snapshot.sql
[2024-03-09T12:22:59.412+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Sales_ETL, task_id=snapshot, execution_date=20240309T115638, start_date=20240309T122259, end_date=20240309T122259
[2024-03-09T12:22:59.425+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 159 for task snapshot (snapshot.sql; 1173)
[2024-03-09T12:22:59.467+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T12:22:59.514+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
