[2024-04-29T10:06:54.291+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Flow.fact_mrr2stg manual__2024-04-29T10:03:23.691759+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
