[2024-03-09T16:36:18.664+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_tables manual__2024-03-09T16:26:12.690000+00:00 [queued]>
[2024-03-09T16:36:18.692+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_tables manual__2024-03-09T16:26:12.690000+00:00 [queued]>
[2024-03-09T16:36:18.693+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 6
[2024-03-09T16:36:18.751+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_tables> on 2024-03-09 16:26:12.690000+00:00
[2024-03-09T16:36:18.762+0000] {standard_task_runner.py:60} INFO - Started process 2611 to run task
[2024-03-09T16:36:18.774+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_tables', 'manual__2024-03-09T16:26:12.690000+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmplixxhm4d']
[2024-03-09T16:36:18.779+0000] {standard_task_runner.py:88} INFO - Job 251: Subtask create_tables
[2024-03-09T16:36:18.999+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator.create_tables manual__2024-03-09T16:26:12.690000+00:00 [running]> on host 3b9d9f11e4f2
[2024-03-09T16:36:19.171+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'create_tables', field 'sql'. Template: 'sql/create.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create.sql
[2024-03-09T16:36:19.183+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create.sql
[2024-03-09T16:36:19.210+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_tables, execution_date=20240309T162612, start_date=20240309T163618, end_date=20240309T163619
[2024-03-09T16:36:19.242+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 251 for task create_tables (sql/create.sql; 2611)
[2024-03-09T16:36:19.277+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T16:36:19.322+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
