[2024-03-12T17:51:48.955+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: ETL_Flow.snapshot manual__2024-03-09T17:34:28.262876+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
